# Generated by Django 5.2.16 on 2026-07-25 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BowlingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.PositiveSmallIntegerField()),
                ('frame_score', models.PositiveIntegerField(default=0)),
                ('is_strike', models.BooleanField(default=False)),
                ('is_spare', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='bowling_game.bowlinggame')),
            ],
            options={
                'ordering': ['frame_number'],
                'unique_together': {('game', 'frame_number')},
            },
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.PositiveSmallIntegerField()),
                ('pins_knocked_down', models.PositiveSmallIntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='bowling_game.frame')),
            ],
            options={
                'ordering': ['roll_number'],
                'unique_together': {('frame', 'roll_number')},
            },
        ),
    ]
